### ISSUE TITLE
Broken -  Generate Certs (first time) wont work

### ISSUE THREAD

**Issue by b-reich** [hispanico/ansible-nginx-revproxy#52]
Hi, i got the following error.

```yaml
- hosts: proxy
  roles:
    - hispanico.nginx_revproxy
  vars:
    nginx_revproxy_sites:
      default:
        ssl: true
        letsencrypt: true

      proxy.reich.dev:
        domains:
          - proxy.reich.dev
        upstreams:
          - { backend_address: 10.0.0.2, backend_port: 80 }
        ssl: true
        letsencrypt: true
```

```
TASK [hispanico.nginx_revproxy : Generate certs (first time)] ************************************************************************************
fatal: [157.90.26.241]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'domains'\n\nThe error appears to be in '/home/benjamin/repos/ansible-test/roles.galaxy/hispanico.nginx_revproxy/tasks/letsencrypt.yml': line 74, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Generate certs (first time)\n  ^ here\n"}
```
